/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sise.ui;

import java.awt.Cursor;
import sise.network.MultiLayerNetwork;
import sise.network.exceptions.CannotCreateNetworkException;
import sise.network.factory.MultiLayerNetworkFactory;
import sise.network.input.InputRow;
import sise.network.input.TrainingDataProvider;
import sise.network.neuron.AbstractNeuron;
import sise.network.strategy.bp.BackPropagationStrategy;
import sise.network.strategy.bp.IdentityActivationBPS;
import sise.network.training.ThresholdEpochNetworkTrainer;
import sise.ui.exceptions.EmptyInputFieldException;
import sise.ui.plot.PlotGenerator;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sise.network.normalization.MinMaxInputNormalizer;
import sise.network.normalization.NumericInputNormalizer;
import sise.ui.generator.TrainingDataGenerator;
import sise.ui.plot.ResultsPlotData;

/**
 *
 * @author PiotrGrzelak
 */
public class ApproximationDialog extends javax.swing.JDialog {

    private PlotGenerator generator;

    private MultiLayerNetwork network;

    private int hiddenNeurons;

    private int inputNeurons;

    private int outputNeurons;

    private double learningRate;

    private double momentumFactor;

    private File trainingFile;

    private File testFile = new File("C:\\Users\\Ardavel\\Desktop\\data\\points = 1000 noise = 0.0.txt");

    private final static NumericInputNormalizer normalizer
            = new MinMaxInputNormalizer(TrainingDataGenerator.MINIMUM,
                    TrainingDataGenerator.MAXIMUM);

    /**
     * Creates new form ApproximationDialog
     *
     * @param parent
     * @param modal
     */
    public ApproximationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        generator = new PlotGenerator();
        initComponents();

        setTitle("Aproksymacja funkcji");

        networkCreationParamsPanel.fixNetworkInputsField(1);
        networkCreationParamsPanel.fixNetworkOutputField(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        headerSeparator = new javax.swing.JSeparator();
        downSeparator = new javax.swing.JSeparator();
        buttonPanel = new javax.swing.JPanel();
        trainNetworkButton = new javax.swing.JButton();
        testNetworkButton = new javax.swing.JButton();
        generateResultsButton = new javax.swing.JButton();
        createNetworkPanel = new javax.swing.JPanel();
        networkCreationSeparator = new javax.swing.JSeparator();
        networkCreationParamsPanel = new sise.ui.NetworkCreationParamsPanel();
        learningParamsInputPanel = new sise.ui.LearningParamsInputPanel();
        createNetworkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aproksymacja");

        headerLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headerLabel.setText("Sieć neuronowa");
        headerPanel.add(headerLabel);

        trainNetworkButton.setText("Trenuj sieć");
        trainNetworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainNetworkButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(trainNetworkButton);

        testNetworkButton.setText("Testuj sieć");
        testNetworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testNetworkButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(testNetworkButton);

        generateResultsButton.setText("Generuj wyniki");
        generateResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateResultsButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(generateResultsButton);

        createNetworkButton.setText("Stwórz sieć");
        createNetworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNetworkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(networkCreationSeparator)
                            .addComponent(headerSeparator)
                            .addComponent(downSeparator)
                            .addComponent(createNetworkButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createNetworkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(learningParamsInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(networkCreationParamsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(networkCreationParamsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createNetworkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createNetworkButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(networkCreationSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(learningParamsInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(downSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trainNetworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainNetworkButtonActionPerformed
        if (network == null) {
            return;
        }

        try {
            File chosenFile;
            if (evt != null) {
                JFileChooser trainingDataFileChooser
                        = new JFileChooser(new File("C:\\Users\\Ardavel\\Desktop\\data"));
                int result = trainingDataFileChooser.showOpenDialog(this);

                if (result == JFileChooser.CANCEL_OPTION) {
                    return;
                }

                chosenFile = trainingDataFileChooser.getSelectedFile();
            } else {
                chosenFile = trainingFile;
            }

            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            TrainingDataProvider provider = new TrainingDataProvider(
                    chosenFile, inputNeurons, outputNeurons, " ", normalizer);
            List<InputRow> trainingData = provider.provideAllRows();

            int maxEpochNum = learningParamsInputPanel.getMaximumEpochNumber();
            learningRate = learningParamsInputPanel.getLearningRate();
            momentumFactor = learningParamsInputPanel.getMomentumFactor();
            double error = learningParamsInputPanel.getErrorThreshold();

            ThresholdEpochNetworkTrainer trainer
                    = new ThresholdEpochNetworkTrainer(maxEpochNum, error, learningRate, momentumFactor);
            List<Double> meanSquaredError = trainer.trainNetwork(network, trainingData);

//            String plotFileName = new PlotNamer().setBaseName("error").setEpochs(meanSquaredError.size()).setHiddenNeurons(hiddenNeurons)
//                    .setLearningRate(learningRate).setMomentumFactor(momentumFactor)
//                    .generateName();
            String description = "N" + hiddenNeurons + "-L" + learningRate + "-M"
                    + momentumFactor;
            String plotFileName = "C:\\Users\\Ardavel\\Desktop\\results\\"
                    + description + " - " + trainingData.size() + ".png";

            generator.generateErrorChart(meanSquaredError, plotFileName);
//            System.out.printf("%s %d %.5f\n", description, meanSquaredError.size(),
//                    meanSquaredError.get(meanSquaredError.size() - 1));
            System.out.printf("%d %.5f ", meanSquaredError.size(),
                    meanSquaredError.get(meanSquaredError.size() - 1));

            if (evt != null) {
                JOptionPane.showMessageDialog(this, "Trening został zakończony");
            }
        } catch (EmptyInputFieldException | IOException ex) {
            Logger.getLogger(ApproximationDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_trainNetworkButtonActionPerformed

    private void testNetworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testNetworkButtonActionPerformed
        try {
            if (network == null) {
                return;
            }

            File chosenFile;
            if (evt != null) {
                JFileChooser trainingDataFileChooser
                        = new JFileChooser(new File("C:\\Users\\Ardavel\\Desktop\\data"));
                int result = trainingDataFileChooser.showOpenDialog(this);

                if (result == JFileChooser.CANCEL_OPTION) {
                    return;
                }
                chosenFile = trainingDataFileChooser.getSelectedFile();
            } else {
                chosenFile = testFile;
            }

            TrainingDataProvider provider = new TrainingDataProvider(
                    chosenFile, inputNeurons, outputNeurons, " ", normalizer);
            List<InputRow> trainingData = provider.provideAllRows();

            List<double[]> networkResults = new ArrayList<>(trainingData.size());
            double overallError = 0;
            for (InputRow row : trainingData) {
                double[] output = network.runNetwork(row.getValues());

                double idealOutput = Math.sqrt(normalizer.denormalize(row.getValues()[0]));
                overallError += Math.pow(idealOutput - output[0], 2);

                networkResults.add(output);
            }
            overallError /= trainingData.size() * 2;

            for (InputRow row : trainingData) {
                double[] values = row.getValues();
                for (int i = 0; i < values.length; ++i) {
                    values[i] = normalizer.denormalize(values[i]);
                }
                row.setValues(values);
            }

            ResultsPlotData resultsPlotData = new ResultsPlotData();
            resultsPlotData.setInputs(trainingData);
            resultsPlotData.setOutputs(networkResults);
            resultsPlotData.setxAxisLabel("arguments");
            resultsPlotData.setyAxisLabel("function values");
            resultsPlotData.setPlotName("Approximation");

            String description = "N" + hiddenNeurons + "-L" + learningRate + "-M"
                    + momentumFactor;
            String plotFileName = "C:\\Users\\Ardavel\\Desktop\\results\\chart-"
                    + description + " - " + trainingData.size() + ".png";

            generator.generateResultsChart(resultsPlotData, plotFileName);

            System.out.printf("%.5f\n", overallError);
//            System.out.printf("%s %.5f\n", description, overallError);
        } catch (IOException ex) {
            Logger.getLogger(ApproximationDialog.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Błąd", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_testNetworkButtonActionPerformed

    private void createNetworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNetworkButtonActionPerformed
        try {
            inputNeurons = networkCreationParamsPanel.getNetworkInputsNum();
            outputNeurons = networkCreationParamsPanel.getNetworkOutputsNum();
            hiddenNeurons = networkCreationParamsPanel.getHiddenNeuronsNum();

            BackPropagationStrategy strategy = BackPropagationStrategy.getInstance();
            IdentityActivationBPS identityStrategy = IdentityActivationBPS.getInstance();
            MultiLayerNetworkFactory factory = new MultiLayerNetworkFactory(
                    new int[]{inputNeurons, hiddenNeurons, outputNeurons}, strategy, true);
            network = factory.createNetwork();
            network.getOutputLayer().getNeurons().stream().forEach((AbstractNeuron n) -> (n.setStrategy(identityStrategy)));

            if (evt != null) {
                JOptionPane.showMessageDialog(this, "Tworzenie sieci zakończone sukcesem", "Sukces",
                        JOptionPane.INFORMATION_MESSAGE);
            }

            trainNetworkButton.setEnabled(true);
            testNetworkButton.setEnabled(true);
        } catch (EmptyInputFieldException | CannotCreateNetworkException ex) {
            Logger.getLogger(ApproximationDialog.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Błąd", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createNetworkButtonActionPerformed

    private void generateResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateResultsButtonActionPerformed
        JFileChooser trainingDataFileChooser
                = new JFileChooser(new File("C:\\Users\\Ardavel\\Desktop\\data"));
        int result = trainingDataFileChooser.showOpenDialog(this);

        if (result == JFileChooser.CANCEL_OPTION) {
            return;
        }
        trainingFile = trainingDataFileChooser.getSelectedFile();

        for (int neurons = 1; neurons <= 10; ++neurons) {
            networkCreationParamsPanel.setNetworkHiddenField(neurons);
            createNetworkButtonActionPerformed(null);
            trainNetworkButtonActionPerformed(null);
            testNetworkButtonActionPerformed(null);
        }
    }//GEN-LAST:event_generateResultsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton createNetworkButton;
    private javax.swing.JPanel createNetworkPanel;
    private javax.swing.JSeparator downSeparator;
    private javax.swing.JButton generateResultsButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JSeparator headerSeparator;
    private sise.ui.LearningParamsInputPanel learningParamsInputPanel;
    private sise.ui.NetworkCreationParamsPanel networkCreationParamsPanel;
    private javax.swing.JSeparator networkCreationSeparator;
    private javax.swing.JButton testNetworkButton;
    private javax.swing.JButton trainNetworkButton;
    // End of variables declaration//GEN-END:variables
}
