/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sise.pietnastka.visual;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import sise.pietnastka.solver.Solution;

/**
 *
 * @author PiotrGrzelak
 */
public class FifteenVisualisation extends javax.swing.JFrame {

    private List<Solution> solvedPuzzles;
    
    /**
     * Creates new form FifteenVisualisation
     */
    public FifteenVisualisation() {
        initComponents();
        solvedPuzzles = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        loadPuzzlesButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        puzzlesLabel = new javax.swing.JLabel();
        puzzlesCombo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        startSimulationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadPuzzlesButton.setText("Wczytaj układanki");
        loadPuzzlesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadPuzzlesButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(loadPuzzlesButton);

        puzzlesLabel.setText("Układanki:");
        jPanel1.add(puzzlesLabel);

        puzzlesCombo.setModel(new DefaultComboBoxModel());
        puzzlesCombo.setMinimumSize(new java.awt.Dimension(250, 30));
        puzzlesCombo.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel1.add(puzzlesCombo);

        startSimulationButton.setText("Pokaż symulację");
        startSimulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSimulationButtonActionPerformed(evt);
            }
        });
        jPanel2.add(startSimulationButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadPuzzlesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadPuzzlesButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File chosenFile = chooser.getSelectedFile();
            try (ObjectInputStream in = new ObjectInputStream(new FileInputStream(chosenFile))) {
                solvedPuzzles = (List<Solution>) in.readObject();
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(FifteenVisualisation.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            DefaultComboBoxModel puzzlesComboModel = (DefaultComboBoxModel) puzzlesCombo.getModel();
            solvedPuzzles.forEach(puzzlesComboModel::addElement);
        }
    }//GEN-LAST:event_loadPuzzlesButtonActionPerformed

    private void startSimulationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSimulationButtonActionPerformed
        Solution solution = (Solution) puzzlesCombo.getSelectedItem();
        if (solution == null) {
            return;
        }
        
        PuzzleDialog dialog = new PuzzleDialog(this, solution);
        dialog.setVisible(true);
        dialog.startSimulation();
    }//GEN-LAST:event_startSimulationButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FifteenVisualisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new FifteenVisualisation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loadPuzzlesButton;
    private javax.swing.JComboBox puzzlesCombo;
    private javax.swing.JLabel puzzlesLabel;
    private javax.swing.JButton startSimulationButton;
    // End of variables declaration//GEN-END:variables
}
