/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sise.pietnastka.visual;

import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.JLabel;

/**
 *
 * @author PiotrGrzelak
 */
public class TilePanel extends javax.swing.JPanel {

    public static final int TILE_WIDTH = 60;
    
    public static final int TILE_HEIGHT = 60;
    
    private JLabel numberLabel;
    
    /**
     * Creates new form TilePanel
     */
    public TilePanel() {
        initComponents();
        numberLabel = new JLabel("");
        numberLabel.setSize(TILE_WIDTH, TILE_HEIGHT);
        Font labelFont = numberLabel.getFont();
        numberLabel.setFont(new Font(labelFont.getName(), Font.PLAIN, labelFont.getSize() * 2));
        this.setLayout(new FlowLayout());
        this.add(numberLabel);
        this.setSize(TILE_WIDTH, TILE_HEIGHT);
        
    }

    public void setNumber(int number) {
        if (number == 0) {
            numberLabel.setText("");
        } else {
            numberLabel.setText(String.valueOf(number));
        }
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
